[workspace]
members = [
	"linked-data",
	"linked-data-derive"
]

resolver = "2"

[workspace.dependencies]
linked-data = { version = "0.1", path = "linked-data" }
linked-data-derive = { version = "0.1", path = "linked-data-derive" }
iref = "3.0"
thiserror = "1.0.47"