[workspace]
members = [
	"serde-ld",
	"serde-ld-derive"
]

resolver = "2"

[workspace.dependencies]
serde-ld = { version = "0.1", path = "serde-ld" }
serde-ld-derive = { version = "0.1", path = "serde-ld-derive" }
iref = "3.0"
thiserror = "1.0.47"