[package]
name = "serde-ld-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.29"
proc-macro2 = "1.0.66"
quote = "1.0.33"
proc-macro-error = "1.0.4"
thiserror = "1.0.47"
iref.workspace = true